# -*- coding: utf-8 -*-
"""preProcessingEx0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQBSU1H08vn8bIRZ_o8D8K2u7QHvq5ke
"""

import numpy as np
import pandas as pd
import sklearn.preprocessing as sk

pandasData = pd.read_csv('/content/data.csv', sep = ',')

df = pd.DataFrame(data=pandasData)

df

"""#### number of instances/rows"""

len(df)

df.isna()

df.isna().values

df.isna().values.any()

df.isnull()

df.isnull().sum()

df.isnull().sum().min()

df.isnull().sum().max()

print(f'minimum missing value(s) : {100*df.isnull().sum().min()/len(df)}%')
print(f'maximum missing value(s) : {100*df.isnull().sum().max()/len(df)}%')

df.isnull().sum().sum()

print(f'Dataset/data frame has {df.isnull().sum().sum()} missing value(s)')

df.isnull().any()

df.loc[:,df.isnull().any()]

df.loc[:,df.isnull().any()].columns[0]

df.loc[:,df.isnull().any()].mean()

df.loc[:,df.isnull().any()].describe()

print(f'Feature of dataset/data frame with missing value(s) is/are "{df.loc[:,df.isnull().any()].columns[0]}"')

!pip install scikit-learn

