# -*- coding: utf-8 -*-
"""Tugas 1 kubik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9MBRpnu02NQfB5fihAXyd_G5eXZXoVO
"""

#Import beberapa command bantuan yang diperlukan
import numpy as np
from scipy.optimize import curve_fit
import pylab
import pandas as pd
import math

def f(x, a3, a2, a1, a0): #Mendefiniskan fungsi yang digunakan
  return a3*x**3 + a2*x**2 + a1*x + a0  #Fungsi yang digunakan
data = pd.read_csv('/content/dataaskom.csv') #Membaca data yang diberikan dalam format csv
x = (data['varX']) #Menjelaskan bahwa variabel x adalah data di kolom varX pada data
y = (data['varY']) #Menjelaskan bahwa variabel y adalah data di kolom varY pada data
init_vals = [1, 1, 1, 1] #Nilai awal yang digunakan
popt, pcov = curve_fit(f, x, y, p0=init_vals) #memulai untuk fitting kurva
print('Best parameter values: {}'.format(popt))

xfitted = np.linspace(x[0], x[len(data)-1], 50) #untuk menghitung data yang cukup banyak
res = y[1] - xfitted[1]
print(res)
pylab.plot(x, y, 'o', label = 'data $(x_i,y_i)$')
pylab.plot(xfitted, f(xfitted, *popt), '-', label = 'fit $f(x_i)$')
pylab.xlabel('x')
pylab.ylabel('y')
pylab.legend()
pylab.show()